# Generated by Django 4.2.4 on 2023-09-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="previous_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
