# Generated by Django 4.2.4 on 2023-10-19 23:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="file1",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="file2",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="file3",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file1",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file3",
        ),
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subjectquestionanswer",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subjectquestionattempt",
            name="subject",
        ),
        migrations.CreateModel(
            name="AttachedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "txt", "mp4"]
                            )
                        ],
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.lesson",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.post",
                    ),
                ),
            ],
        ),
    ]
