# Generated by Django 4.2.4 on 2023-10-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0002_remove_lesson_file1_remove_lesson_file2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
