# Generated by Django 4.2.4 on 2023-09-21 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0002_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
