# Generated by Django 4.2.4 on 2023-11-05 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0003_alter_lesson_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectquestionattempt",
            name="question",
        ),
        migrations.RemoveField(
            model_name="subjectquestionattempt",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subjectstudentscore",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subjectstudentscore",
            name="user",
        ),
        migrations.DeleteModel(
            name="SubjectQuestionAnswer",
        ),
        migrations.DeleteModel(
            name="SubjectQuestionAttempt",
        ),
        migrations.DeleteModel(
            name="SubjectStudentScore",
        ),
    ]
