# Generated by Django 4.2.7 on 2023-11-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_remove_subjectquestionattempt_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
