# Generated by Django 3.2.22 on 2023-11-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_quiz_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_a', models.IntegerField(default=90)),
                ('grade_b', models.IntegerField(default=80)),
                ('grade_c', models.IntegerField(default=70)),
                ('grade_d', models.IntegerField(default=60)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.subject')),
            ],
        ),
    ]
