# Generated by Django 3.2.22 on 2023-11-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_grade_gradescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescale',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learn.subject'),
        ),
    ]
