# Generated by Django 4.2.4 on 2023-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0007_alter_post_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
