# Generated by Django 4.2.4 on 2023-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0010_quiz_results_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
