# Generated by Django 4.2.4 on 2023-09-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0011_lesson_image_alter_lesson_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="file",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
