# Generated by Django 4.2.4 on 2023-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0012_alter_lesson_file_alter_lesson_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="file",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file",
        ),
        migrations.AddField(
            model_name="lesson",
            name="file1",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="file2",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="file3",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="youtubevideo",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="post",
            name="file1",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="post",
            name="file2",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="post",
            name="file3",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
