# Generated by Django 4.2.4 on 2023-09-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0014_student_studentanswer_takenquiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
