# Generated by Django 4.2.4 on 2023-09-28 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0015_alter_post_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "txt"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="file1",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file3",
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.ManyToManyField(blank=True, to="learn.file"),
        ),
    ]
