# Generated by Django 4.2.4 on 2023-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0016_file_remove_post_file1_remove_post_file2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="files",
        ),
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.FileField(blank=True, upload_to="", verbose_name="File"),
        ),
    ]
