# Generated by Django 4.2.4 on 2023-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0018_remove_post_files_post_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="files",
        ),
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.FileField(blank=True, upload_to="", verbose_name="File"),
        ),
    ]
