# Generated by Django 4.2.4 on 2023-09-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0020_remove_post_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.ManyToManyField(blank=True, to="learn.file"),
        ),
    ]
