# Generated by Django 4.2.4 on 2023-09-28 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0021_post_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="files",
        ),
    ]
