# Generated by Django 4.2.4 on 2023-09-29 00:21

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0022_remove_post_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
        migrations.AddField(
            model_name="post",
            name="file1",
            field=models.FileField(
                blank=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="file2",
            field=models.FileField(
                blank=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="file3",
            field=models.FileField(
                blank=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
